export const ONSUBMIT_ADDCONTACT = "ONSUBMIT_ADDCONTACT";
export const ONSUBMIT_EDITCONTACT = "ONSUBMIT_EDITCONTACT";
export const ONVIEWCONTACT = "ONVIEWCONTACT";

export const ONCHANGE_LOGUSER = "ONCHANGE_LOGUSER";
export const ONCLICK_MSGBOX = "ONCLICK_MSGBOX";
export const ONADD_MSGUSER = "ONADD_MSGUSER";

export const RANDOM_BGCOLOR = "RANDOM_BGCOLOR";